### PR TITLE
Fix auth port mess and adding a user

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by pmac** [comment]
@willkg I believe this should fix things. Give it a shot when you get a min.

**Comment by willkg** [comment]
When I try to connect to `http://localhost:8000`, there's nothing listening on that port.

When I do `make run`, I get some output including this:

```
assets_1      | [Browsersync] Proxying: http://app:3000
assets_1      | [Browsersync] Access URLs:
assets_1      |  -----------------------------------
assets_1      |        Local: http://localhost:3000
assets_1      |     External: http://172.21.0.2:3000
assets_1      |  -----------------------------------
assets_1      |           UI: http://localhost:3001
assets_1      |  UI External: http://172.21.0.2:3001
assets_1      |  -----------------------------------
```

That seems wrong. Shouldn't it be `Local: http://localhost:8000`? The changes look fine, so I'm not sure what's missing or whether I've got something local set up wrong.

**Comment by pmac** [comment]
You'll have to rebuild all of the images. Did that happen?

**Comment by willkg** [comment]
Aha! I didn't know I had to rebuild. After doing that, everything works super!

**Pull request merged**
