### PR TITLE
Switch to python-3.6-alpine base image

### PR DESCRIPTION
**Pull request by pmac**
* Slimmer and easier to use base image
* Based on official Python image so most up to date
* Remove supervisor so no longer also need Python 2.7
* Remove dependency on libmemcache since non longer installing pylibmc

Mostly doing this as cleanup since this is the new best base image we're using on our team. [The docker file](https://github.com/mozmar/docker-base-alpine/blob/master/Dockerfile.py36) is very simple and maintained by the marketing ops team. Let me know what you think.

### CODE REVIEW

**Comment by willkg** [comment]
I love this--I think it's a great idea.

I get an error when doing `make rebuild`:

```
(<detached:remotes/official/pr/386=ee5f6) ~/mozilla/standup> make rebuild
# python related things
rm -rf build/
rm -rf dist/
rm -rf .eggs/
find . -name '*.egg-info' -exec rm -rf {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '__pycache__' -exec rm -rf {} +
# test related things
rm -f .coverage
# docs files
rm -rf docs/_build/
# state files
rm -f .docker-build*
make build
make[1]: Entering directory '/home/willkg/mozilla/standup'
make build-base
make[2]: Entering directory '/home/willkg/mozilla/standup'
/home/willkg/.local/bin/docker-compose -f docker-compose.build.yml build --pull base
Building base
ERROR: Error processing tar file(archive/tar: invalid tar header):
Makefile:30: recipe for target 'build-base' failed
make[2]: *** [build-base] Error 1
make[2]: Leaving directory '/home/willkg/mozilla/standup'
Makefile:24: recipe for target '.docker-build-base' failed
make[1]: *** [.docker-build-base] Error 2
make[1]: Leaving directory '/home/willkg/mozilla/standup'
Makefile:27: recipe for target '.docker-build' failed
make: *** [.docker-build] Error 2
```

Am I doing something wrong?

**Comment by pmac** [comment]
I don't think so. `make rebuild` is all I did as well... I'll see if I can reproduce.

**Comment by willkg** [comment]
I've got docker-compose 1.13.0. Maybe it's related to the version I'm using?

**Comment by willkg** [comment]
@pmac If you don't figure this out, I'll spend more time on it tomorrow.

**Comment by willkg** [comment]
I figured it out. For some reason if I have a file in my directory tree that's not owned by me, then the docker engine fails and (probably) returns an unhelpful message to docker-compose that gives an even more unhelpful message.

**Comment by pmac** [comment]
Oh wow. What a strange error state. Especially since that is a common occurrence with docker volumes since they commonly run as root and create root owned files in the dir. Thanks for checking it out!

**Comment by pmac** [comment]
@willkg I've just pushed another commit that moves asset building to a separate image so that we no longer have nodejs installed in our production images. It's a little confusing. Let me know if you'd like to chat about it more real-time.

**Comment by willkg** [comment]
I'm pretty overwhelmed at the moment. I can take a look at this later this week maybe. Is that ok?

**Comment by pmac** [comment]
absolutely! no rush and no requirement. I think I like it, but always value your feedback. this isn't fixing an active issue, so let's take our time.

**Comment by willkg** [comment]
I went through and this looks good to me. r+

**Pull request merged**
