### PR TITLE
Fix #220: Add CSP

### LINKED ISSUE #220: Implement Content-Security-Policy
Standup should implement Content-Security-Policy (CSP), as a safeguard against XSS.

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by freddyb** [comment]
For a safe CSP, you should also set object-src to `'none'`.

**Comment by pmac** [comment]
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#object-src) it falls back to "default-src" if not defined, which in our case is just `'self'`. Is that not good?

**Comment by pmac** [comment]
@freddyb opinions on my last comment? I've looked into other implementations as well (like github's) and they don't set object-src at all, but they do have `default-src 'none'`.

**Comment by pmac** [comment]
I've updated things to be better based on some new understanding, and I think this is a cleaner config as well. Let me know what you all think.

/cc @freddyb @willkg

**Comment by freddyb** [comment]
Sorry for the long wait. Looks good.

**Comment by pmac** [comment]
I think this is in good shape. Let's get it in an test it on stage.

**Pull request merged**
